# Polities


**Start here if precheck.R is done**
  
```{r polities}

Vars <- as.matrix(read.csv('variables.csv', header=TRUE))
Vars <- Vars[Vars[,6]==Section1 | Vars[,6]==Section2 | Vars[,6]==Section3,] # Reduce the variables list to the Section set above

Vars[,1] <- paste(Vars[,2],Vars[,1]) # Creating unique variable/section combinations

Vars_df <- read_csv("variables.csv")

polities <- 
  read.csv('polities.csv', header=TRUE) %>% 
  filter(!NGA %in% c("Crete", "Galilee", "Middle Ganga")) %>%  # Remove new NGAs
  filter(!polID %in% c("IdCJBun", "IdKalin")) %>%  # Remove low-coverage polities causing bugs in C. Java)
  filter(!polID %in% c("EsHabsb", "USIllinL", "GbEmpir", "InEInCo", "InBritP", "RuYakuL", "UsIroqL")) #Remove post-colonial polities (also see below for removing post-colonial polities from NGAs with only 2 polities)

NGAs <- levels(polities$NGA)

nrep <- 20
ImpDatRepl <- matrix(NA, nrow=0, ncol=0) 
for(irep in 1:nrep){
  print(irep)
  source("ConstrMI.R")
  source("AggrMI.R")
  source("ImputeMI.R")
  ones <- matrix(data=1,nrow=length(AggrDat[,1]),ncol=1)
  colnames(ones) <- "irep"
  ImpDat <- cbind(AggrDat[,1:4],ImpDat,(ones*irep),AggrDat[,14:32])
  ImpDatRepl <- rbind(ImpDatRepl,ImpDat)
}
```


Remove polity-dates that didn't yield 20 repl and post-colonial polities that couldn't be removed from multiple imputation due to bugs with only 1 polity/NGA

```{r}

polities <- read.csv('polities.csv', header=TRUE)
polities <- polities[polities$PolID != "InGaroL",] # removing here because it caused bugs earlier
write.csv(polities, file="polities.csv",  row.names=FALSE) 
polities <- polities[polities$PolID != "CnHChin",] # removing here because it caused bugs earlier
write.csv(polities, file="polities.csv",  row.names=FALSE) 
polities <- polities[polities$PolID != "PgOrokL",] # removing here because it caused bugs earlier
write.csv(polities, file="polities.csv",  row.names=FALSE) 

ImpDatRepl <- ImpDatRepl[ImpDatRepl$PolID != "InGaroL",] # removing here because it seemed to create bugs when you have only 1 polity in an NGA, so couldn't remove earlier
ImpDatRepl <- ImpDatRepl[ImpDatRepl$PolID != "CnHChin",] # removing here because it seemed to create bugs when you have only 1 polity in an NGA, so couldn't remove earlier
ImpDatRepl <- ImpDatRepl[ImpDatRepl$PolID != "PgOrokL",] # removing here because it seemed to create bugs when you have only 1 polity in an NGA, so couldn't remove earlier



dat_temp <- ImpDatRepl
for(i in 1:nrow(polities)){
  dat <- ImpDatRepl[as.character(ImpDatRepl[,2])==as.character(polities[i,2]),]
  if(nrow(dat)!=0){
    Time <- unique(dat$Time)
    for(j in 1:length(Time)){
      dt <- dat[dat$Time==Time[j],]
      if(nrow(dt) != nrep){
        print(nrow(dt))
        print(dt[1,1:3])
        dat_temp[as.character(dat_temp$PolID)==as.character(dat$PolID[1]) & dat_temp$Time==Time[j],14] <- -99999
      }
    }
  }
}
ImpDatRepl <- dat_temp[dat_temp$irep!=-99999,]



write.csv(ImpDatRepl, file="ImpDatRepl.csv",  row.names=FALSE)
#  end of the new scrape section
```



